In [1]:
import os
from tqdm import tqdm
import mysql.connector
import pandas as pd
from dotenv import load_dotenv
load_dotenv()
host=os.getenv('host')
user=os.getenv('user')
password=os.getenv('password')
database=os.getenv('database')
mydb = mysql.connector.connect(
  host=host,
  user=user,
  password=password,
  database=database
)
mycursor = mydb.cursor()

In [8]:
query = """
select u.userid, u.favorite_genre, group_concat(distinct f.id separator ', ') as artist_id from user as u
inner join favorite as f on u.userid = f.user_id and f.type = "artist"
group by u.userid;
"""
mycursor.execute(query)

data = mycursor.fetchall()

print(data)

mydb.commit()
# df2 = pd.DataFrame(df1, columns=["usename", "password", "favorite_genre", "image", "email", "userid"])
# df2.head()

[(1, None, '0EmeFodog0BfCgMzAIvKQp, 3Nrfpe0tUJi4K4DXYWgMUX, 4VMYDCV2IEDYJArk749S6m, 66CXWjxzNUsdJxJ2JdwvnR, 6eUKZXaKkcviH0Ku9w2n3V, 6l3HvQ5sa6mXTsMTB19rO5, 6LuN9FCkKOj5PcnpouEgny'), (2, 'acoustic, afrobeat', '00FQb4jTyendYWaN8pK0wa, 0Y5tJX1MQlPlqiwlOH1tJY, 41MozSoPIsD1dJM0CLPjZF, 66CXWjxzNUsdJxJ2JdwvnR'), (3, '', '1VPmR4DJC1PlOtd0IADAO0, 246dkjvS1zLTtiykXe5h60, 2R21vXR83lH98kGeO99Y66, 4gzpq5DPGxSnKTe4SA8HAU, 4q3ewBCX7sLwd24euuV69X, 5K4W6rqBFWDnAN6FQUkS6x, 6l3HvQ5sa6mXTsMTB19rO5'), (4, 'tango, techno, trance', '1Cs0zKBU1kc0i8ypK3B9ai, 2R21vXR83lH98kGeO99Y66, 3MZsBdqDrRTJihTHQrO6Dq, 3TVXtAsR1Inumwj472S9r4, 4VMYDCV2IEDYJArk749S6m, 6l3HvQ5sa6mXTsMTB19rO5, 6M2wZ9GZgrQXHCFfjv46we, 7Ln80lUS6He07XvHI8qqHH'), (5, 'rock, pop, indie-pop, dance', '00FQb4jTyendYWaN8pK0wa, 0du5cEVh5yTK9QJze8zA0C, 0EmeFodog0BfCgMzAIvKQp, 0Y5tJX1MQlPlqiwlOH1tJY, 2YZyLoL8N0Wb9xBt1NhZWg, 6l3HvQ5sa6mXTsMTB19rO5, 790FomKkXshlbRYZFtlgla, 7Ln80lUS6He07XvHI8qqHH'), (6, 'jazz, blues, soul, funk', '0du5cEVh5yTK9QJze8zA0C, 0hCNtLu0JehylgoiP8L4Gh, 4YRxDV8wJFPHPTeXepOstw, 5K4W6rqBFWDnAN6FQUkS6x'), (7, 'edm, house, electro, electronic', '00FQb4jTyendYWaN8pK0wa, 0Y5tJX1MQlPlqiwlOH1tJY, 5K4W6rqBFWDnAN6FQUkS6x, 5pKCCKE2ajJHZ9KAiaK11H, 6l3HvQ5sa6mXTsMTB19rO5, 6M2wZ9GZgrQXHCFfjv46we, 716NhGYqD1jl2wI1Qkgq36, 7bXgB6jMjp9ATFy66eO08Z'), (8, 'hip-hop', '1Cs0zKBU1kc0i8ypK3B9ai, 4gzpq5DPGxSnKTe4SA8HAU, 5pKCCKE2ajJHZ9KAiaK11H, 7bXgB6jMjp9ATFy66eO08Z, 7ltDVBr6mKbRvohxheJ9h1'), (9, 'classical, piano, opera', '00FQb4jTyendYWaN8pK0wa, 1RyvyyTE3xzB2ZywiAwp0i, 1vyhD5VmyZ7KMfW5gqLgo5, 1Xyo4u8uXC1ZmMpatF05PJ, 2LRoIwlKmHjgvigdNGBHNo, 3MZsBdqDrRTJihTHQrO6Dq, 4O15NlyKLIASxsJ0PrXPfz, 4YRxDV8wJFPHPTeXepOstw, 5f7VJjfbwm532GiveGC0ZK, 6l3HvQ5sa6mXTsMTB19rO5, 6M2wZ9GZgrQXHCFfjv46we'), (10, 'k-pop, pop, dance, party', '1i8SpTcr7yvPOmcqrbnVXY, 1McMsnEElThX1knmY4oliG, 3Nrfpe0tUJi4K4DXYWgMUX, 41MozSoPIsD1dJM0CLPjZF, 53XhwfbYqKCa1cC15pYq2q'), (11, 'metal, heavy-metal, metalcore, hard-rock', '06HL4z0CvFAxyc27GXpf02, 1Cs0zKBU1kc0i8ypK3B9ai, 790FomKkXshlbRYZFtlgla, 7Ln80lUS6He07XvHI8qqHH'), (12, 'ambient, chill, sleep, new-age', '2LRoIwlKmHjgvigdNGBHNo, 3Nrfpe0tUJi4K4DXYWgMUX'), (13, 'funk, disco, groove', '1Cs0zKBU1kc0i8ypK3B9ai, 1McMsnEElThX1knmY4oliG, 41MozSoPIsD1dJM0CLPjZF, 6qqNVTkY8uBg9cP3Jd7DAH'), (14, 'country, folk, singer-songwriter', '1vyhD5VmyZ7KMfW5gqLgo5, 4YRxDV8wJFPHPTeXepOstw, 53XhwfbYqKCa1cC15pYq2q, 66CXWjxzNUsdJxJ2JdwvnR, 6M2wZ9GZgrQXHCFfjv46we, 6vWDO969PvNqNYHIOW5v0m'), (15, 'techno, minimal-techno, detroit-techno', '0du5cEVh5yTK9QJze8zA0C, 1McMsnEElThX1knmY4oliG, 1uNFoZAHBGtllmzznpCI3s, 53XhwfbYqKCa1cC15pYq2q, 5f7VJjfbwm532GiveGC0ZK, 5K4W6rqBFWDnAN6FQUkS6x, 6l3HvQ5sa6mXTsMTB19rO5, 6LuN9FCkKOj5PcnpouEgny, 716NhGYqD1jl2wI1Qkgq36, 7dGJo4pcD2V6oG8kP0tJRR'), (16, 'dubstep, drum-and-bass, breakbeat', '1i8SpTcr7yvPOmcqrbnVXY, 1RyvyyTE3xzB2ZywiAwp0i, 4O15NlyKLIASxsJ0PrXPfz, 5pKCCKE2ajJHZ9KAiaK11H, 66CXWjxzNUsdJxJ2JdwvnR, 6l3HvQ5sa6mXTsMTB19rO5'), (17, 'romance, sad, acoustic', '1Cs0zKBU1kc0i8ypK3B9ai, 1mcTU81TzQhprhouKaTkpq, 4MCBfE4596Uoi2O4DtmEMz, 6M2wZ9GZgrQXHCFfjv46we, 6vWDO969PvNqNYHIOW5v0m'), (18, 'punk, punk-rock, hardcore', '1mcTU81TzQhprhouKaTkpq, 1URnnhqYAYcrqrcwql10ft, 3MZsBdqDrRTJihTHQrO6Dq, 4MCBfE4596Uoi2O4DtmEMz, 4O15NlyKLIASxsJ0PrXPfz, 53XhwfbYqKCa1cC15pYq2q, 66CXWjxzNUsdJxJ2JdwvnR, 6LuN9FCkKOj5PcnpouEgny, 6M2wZ9GZgrQXHCFfjv46we'), (19, 'gospel, soul, blues', '00FQb4jTyendYWaN8pK0wa, 1Cs0zKBU1kc0i8ypK3B9ai, 1mcTU81TzQhprhouKaTkpq, 1VPmR4DJC1PlOtd0IADAO0, 3TVXtAsR1Inumwj472S9r4, 5f7VJjfbwm532GiveGC0ZK, 6eUKZXaKkcviH0Ku9w2n3V, 790FomKkXshlbRYZFtlgla, 7dGJo4pcD2V6oG8kP0tJRR'), (20, 'indie-pop, emo, pop', '00FQb4jTyendYWaN8pK0wa, 0Y5tJX1MQlPlqiwlOH1tJY, 1Cs0zKBU1kc0i8ypK3B9ai, 1i8SpTcr7yvPOmcqrbnVXY, 3TVXtAsR1Inumwj472S9r4, 41MozSoPIsD1dJM0CLPjZF, 4O15NlyKLIASxsJ0PrXPfz, 6l3HvQ5sa6mXTsMTB19rO5'), (21, 'house, deep-house, progressive-house', '0EmeFodog0BfCgMzAIvKQp, 0Y5tJX1MQlPlqiwlOH1tJY, 1mcTU81TzQhprhouKaTkpq, 6eUKZXaKkcviH0Ku9w2n3V, 6l3HvQ5sa6mXTsMTB19rO5, 6vWDO969PvNqNYHIOW5v0m'), (22, 'salsa, samba, tango', '00FQb4jTyendYWaN8pK0wa, 3Nrfpe0tUJi4K4DXYWgMUX, 4O15NlyKLIASxsJ0PrXPfz, 6l3HvQ5sa6mXTsMTB19rO5, 790FomKkXshlbRYZFtlgla'), (23, 'spanish, romance', '06HL4z0CvFAxyc27GXpf02, 0du5cEVh5yTK9QJze8zA0C, 1i8SpTcr7yvPOmcqrbnVXY, 246dkjvS1zLTtiykXe5h60, 2YZyLoL8N0Wb9xBt1NhZWg, 53XhwfbYqKCa1cC15pYq2q, 5pKCCKE2ajJHZ9KAiaK11H, 66CXWjxzNUsdJxJ2JdwvnR, 790FomKkXshlbRYZFtlgla'), (24, 'german, techno, trance', '0Y5tJX1MQlPlqiwlOH1tJY, 2LRoIwlKmHjgvigdNGBHNo, 2R21vXR83lH98kGeO99Y66, 53XhwfbYqKCa1cC15pYq2q, 6l3HvQ5sa6mXTsMTB19rO5, 6M2wZ9GZgrQXHCFfjv46we'), (25, 'french, pop, electro', '0EmeFodog0BfCgMzAIvKQp, 1Xyo4u8uXC1ZmMpatF05PJ, 246dkjvS1zLTtiykXe5h60, 5f7VJjfbwm532GiveGC0ZK, 6qqNVTkY8uBg9cP3Jd7DAH'), (26, 'guitar, rock, hard-rock', '0hCNtLu0JehylgoiP8L4Gh, 1Cs0zKBU1kc0i8ypK3B9ai, 6KImCVD70vtIoJWnq6nGn3'), (27, 'emo, indie-pop', '4O15NlyKLIASxsJ0PrXPfz, 4YRxDV8wJFPHPTeXepOstw, 5f7VJjfbwm532GiveGC0ZK, 6vWDO969PvNqNYHIOW5v0m'), (28, 'dancehall, dub', '1VPmR4DJC1PlOtd0IADAO0, 1Xyo4u8uXC1ZmMpatF05PJ, 3TVXtAsR1Inumwj472S9r4, 4gzpq5DPGxSnKTe4SA8HAU, 4YRxDV8wJFPHPTeXepOstw, 6l3HvQ5sa6mXTsMTB19rO5'), (29, 'club, party, dance', '0Y5tJX1MQlPlqiwlOH1tJY, 1i8SpTcr7yvPOmcqrbnVXY, 1vyhD5VmyZ7KMfW5gqLgo5, 1Xyo4u8uXC1ZmMpatF05PJ, 4q3ewBCX7sLwd24euuV69X, 790FomKkXshlbRYZFtlgla, 7ltDVBr6mKbRvohxheJ9h1'), (30, 'new-age, ambient, chill', '1Cs0zKBU1kc0i8ypK3B9ai, 1uNFoZAHBGtllmzznpCI3s, 1VPmR4DJC1PlOtd0IADAO0, 2YZyLoL8N0Wb9xBt1NhZWg, 4gzpq5DPGxSnKTe4SA8HAU, 53XhwfbYqKCa1cC15pYq2q, 5cj0lLjcoR7YOSnhnX0Po5, 5K4W6rqBFWDnAN6FQUkS6x, 7bXgB6jMjp9ATFy66eO08Z, 7ltDVBr6mKbRvohxheJ9h1'), (31, 'ska, punk, rock-n-roll', '0EmeFodog0BfCgMzAIvKQp, 1Xyo4u8uXC1ZmMpatF05PJ, 3Nrfpe0tUJi4K4DXYWgMUX, 3TVXtAsR1Inumwj472S9r4, 6qqNVTkY8uBg9cP3Jd7DAH'), (32, 'show-tunes, opera, classical', '1RyvyyTE3xzB2ZywiAwp0i, 4MCBfE4596Uoi2O4DtmEMz, 66CXWjxzNUsdJxJ2JdwvnR, 6l3HvQ5sa6mXTsMTB19rO5, 6vWDO969PvNqNYHIOW5v0m'), (33, 'afrobeat, funk, groove', '1i8SpTcr7yvPOmcqrbnVXY, 246dkjvS1zLTtiykXe5h60, 3Nrfpe0tUJi4K4DXYWgMUX, 6qqNVTkY8uBg9cP3Jd7DAH, 7Ln80lUS6He07XvHI8qqHH, 7ltDVBr6mKbRvohxheJ9h1'), (34, 'cantopop, pop, k-pop', '06HL4z0CvFAxyc27GXpf02, 1McMsnEElThX1knmY4oliG, 1uNFoZAHBGtllmzznpCI3s, 1URnnhqYAYcrqrcwql10ft, 2LRoIwlKmHjgvigdNGBHNo, 5K4W6rqBFWDnAN6FQUkS6x'), (35, 'industrial, electro, electronic', '06HL4z0CvFAxyc27GXpf02, 0du5cEVh5yTK9QJze8zA0C, 0hCNtLu0JehylgoiP8L4Gh, 15UsOTVnJzReFVN1VCnxy4, 1Cs0zKBU1kc0i8ypK3B9ai, 1i8SpTcr7yvPOmcqrbnVXY, 1McMsnEElThX1knmY4oliG, 1URnnhqYAYcrqrcwql10ft, 3TVXtAsR1Inumwj472S9r4, 4O15NlyKLIASxsJ0PrXPfz, 6eUKZXaKkcviH0Ku9w2n3V, 6LuN9FCkKOj5PcnpouEgny'), (36, 'trip-hop, chill, ambient', '1i8SpTcr7yvPOmcqrbnVXY, 1URnnhqYAYcrqrcwql10ft, 3MZsBdqDrRTJihTHQrO6Dq, 6l3HvQ5sa6mXTsMTB19rO5, 7bXgB6jMjp9ATFy66eO08Z'), (37, 'grindcore, death-metal, black-metal', '1URnnhqYAYcrqrcwql10ft, 2LRoIwlKmHjgvigdNGBHNo, 6M2wZ9GZgrQXHCFfjv46we, 7Ln80lUS6He07XvHI8qqHH, 7ltDVBr6mKbRvohxheJ9h1'), (38, 'hardstyle, edm, dance', '0EmeFodog0BfCgMzAIvKQp, 3TVXtAsR1Inumwj472S9r4, 41MozSoPIsD1dJM0CLPjZF, 4MCBfE4596Uoi2O4DtmEMz, 5pKCCKE2ajJHZ9KAiaK11H, 716NhGYqD1jl2wI1Qkgq36, 7dGJo4pcD2V6oG8kP0tJRR'), (39, 'forro, samba, salsa', '00FQb4jTyendYWaN8pK0wa, 0hCNtLu0JehylgoiP8L4Gh, 1URnnhqYAYcrqrcwql10ft, 2YZyLoL8N0Wb9xBt1NhZWg, 4VMYDCV2IEDYJArk749S6m, 5K4W6rqBFWDnAN6FQUkS6x'), (40, 'sertanejo, country, folk', '1Cs0zKBU1kc0i8ypK3B9ai, 1RyvyyTE3xzB2ZywiAwp0i, 2YZyLoL8N0Wb9xBt1NhZWg, 3Nrfpe0tUJi4K4DXYWgMUX, 5f7VJjfbwm532GiveGC0ZK, 790FomKkXshlbRYZFtlgla, 7bXgB6jMjp9ATFy66eO08Z'), (41, 'garage, house, club', '00FQb4jTyendYWaN8pK0wa, 1URnnhqYAYcrqrcwql10ft, 3MZsBdqDrRTJihTHQrO6Dq, 5K4W6rqBFWDnAN6FQUkS6x'), (42, 'psych-rock, rock, indie-pop', '1Cs0zKBU1kc0i8ypK3B9ai, 1uNFoZAHBGtllmzznpCI3s, 1Xyo4u8uXC1ZmMpatF05PJ, 2YZyLoL8N0Wb9xBt1NhZWg, 53XhwfbYqKCa1cC15pYq2q, 7dGJo4pcD2V6oG8kP0tJRR'), (43, 'power-pop, pop', '6LuN9FCkKOj5PcnpouEgny'), (44, 'sad, piano, acoustic', '2R21vXR83lH98kGeO99Y66, 4q3ewBCX7sLwd24euuV69X, 4VMYDCV2IEDYJArk749S6m, 5K4W6rqBFWDnAN6FQUkS6x, 66CXWjxzNUsdJxJ2JdwvnR, 6KImCVD70vtIoJWnq6nGn3, 790FomKkXshlbRYZFtlgla'), (45, 'swedish, pop, edm', '00FQb4jTyendYWaN8pK0wa, 1vyhD5VmyZ7KMfW5gqLgo5, 246dkjvS1zLTtiykXe5h60'), (46, 'indian, classical', '1URnnhqYAYcrqrcwql10ft, 3TVXtAsR1Inumwj472S9r4, 4MCBfE4596Uoi2O4DtmEMz, 66CXWjxzNUsdJxJ2JdwvnR, 7bXgB6jMjp9ATFy66eO08Z, 7Ln80lUS6He07XvHI8qqHH'), (47, 'spanish, guitar', '15UsOTVnJzReFVN1VCnxy4, 1i8SpTcr7yvPOmcqrbnVXY, 1RyvyyTE3xzB2ZywiAwp0i, 2LRoIwlKmHjgvigdNGBHNo, 3TVXtAsR1Inumwj472S9r4, 6vWDO969PvNqNYHIOW5v0m'), (48, 'soul, funk', '1McMsnEElThX1knmY4oliG, 2YZyLoL8N0Wb9xBt1NhZWg, 3MZsBdqDrRTJihTHQrO6Dq, 41MozSoPIsD1dJM0CLPjZF'), (49, 'electronic, edm, electro', '00FQb4jTyendYWaN8pK0wa, 1Xyo4u8uXC1ZmMpatF05PJ, 6M2wZ9GZgrQXHCFfjv46we, 6qqNVTkY8uBg9cP3Jd7DAH'), (50, 'rock-n-roll, blues, guitar', '1URnnhqYAYcrqrcwql10ft, 1vyhD5VmyZ7KMfW5gqLgo5, 4MCBfE4596Uoi2O4DtmEMz, 6eUKZXaKkcviH0Ku9w2n3V')]

In [9]:
import pandas as pd


df1 = pd.DataFrame(data, columns=[
    "uid", "favorite_genre", "artist_id"
])
df1.head()

,uid,favorite_genre,artist_id
0,1,NaN,"0EmeFodog0BfCgMzAIvKQp, 3Nrfpe0tUJi4K4DXYWgMUX..."
1,2,"acoustic, afrobeat","00FQb4jTyendYWaN8pK0wa, 0Y5tJX1MQlPlqiwlOH1tJY..."
2,3,,"1VPmR4DJC1PlOtd0IADAO0, 246dkjvS1zLTtiykXe5h60..."
3,4,"tango, techno, trance","1Cs0zKBU1kc0i8ypK3B9ai, 2R21vXR83lH98kGeO99Y66..."
4,5,"rock, pop, indie-pop, dance","00FQb4jTyendYWaN8pK0wa, 0du5cEVh5yTK9QJze8zA0C..."

In [10]:
GENRES = [
    "acoustic","afrobeat","alt-rock","ambient","black-metal","blues","breakbeat",
    "cantopop","chicago-house","chill","classical","club","comedy","country",
    "dance","dancehall","death-metal","deep-house","detroit-techno","disco",
    "drum-and-bass","dub","dubstep","edm","electro","electronic","emo","folk",
    "forro","french","funk","garage","german","gospel","goth","grindcore",
    "groove","guitar","hard-rock","hardcore","hardstyle","heavy-metal","hip-hop",
    "house","indian","indie-pop","industrial","jazz","k-pop","metal","metalcore",
    "minimal-techno","new-age","opera","party","piano","pop","pop-film",
    "power-pop","progressive-house","psych-rock","punk","punk-rock","rock",
    "rock-n-roll","romance","sad","salsa","samba","sertanejo","show-tunes",
    "singer-songwriter","ska","sleep","songwriter","soul","spanish","swedish",
    "tango","techno","trance","trip-hop"
]

def build_user_genre_matrix(df1):
    # chỉ lấy 2 cột cần
    df = df1[["uid", "favorite_genre"]].copy()

    # xử lý null / rỗng
    df["favorite_genre"] = df["favorite_genre"].fillna("")
    
    # tách list genre
    df["favorite_genre"] = df["favorite_genre"].apply(
        lambda x: [g.strip() for g in x.split(",") if g.strip()]
    )

    # explode
    df = df.explode("favorite_genre")

    # tạo one-hot
    df = pd.get_dummies(df, columns=["favorite_genre"])

    # group lại theo user
    df = df.groupby("uid").max().reset_index()

    # đảm bảo đủ tất cả genre
    for g in GENRES:
        col = f"favorite_genre_{g}"
        if col not in df.columns:
            df[col] = 0

    # rename cho gọn
    df.columns = [c.replace("favorite_genre_", "") for c in df.columns]

    # sắp xếp cột
    df = df[["uid"] + GENRES]

    return df


df2 = build_user_genre_matrix(df1)
df2 = df2.astype(int)
print(df2.head())

   uid  acoustic  afrobeat  alt-rock  ambient  black-metal  blues  breakbeat  \
0    1         0         0         0        0            0      0          0
1    2         1         1         0        0            0      0          0
2    3         0         0         0        0            0      0          0
3    4         0         0         0        0            0      0          0
4    5         0         0         0        0            0      0          0

   cantopop  chicago-house  ...  ska  sleep  songwriter  soul  spanish  \
0         0              0  ...    0      0           0     0        0
1         0              0  ...    0      0           0     0        0
2         0              0  ...    0      0           0     0        0
3         0              0  ...    0      0           0     0        0
4         0              0  ...    0      0           0     0        0

   swedish  tango  techno  trance  trip-hop
0        0      0       0       0         0
1        0      0       0       0         0
2        0      0       0       0         0
3        0      1       1       1         0
4        0      0       0       0         0

[5 rows x 83 columns]

In [11]:
import numpy as np

def cosine_sim(u1, u2):
    u1 = np.array(u1)
    u2 = np.array(u2)

    dot = np.dot(u1, u2)
    norm_u1 = np.linalg.norm(u1)
    norm_u2 = np.linalg.norm(u2)

    if norm_u1 == 0 or norm_u2 == 0:
        return 0  # tránh chia 0

    return dot / (norm_u1 * norm_u2)

In [12]:
def get_similarity(df2, target_vec, cols_id):
    X = df2.drop(cols_id, axis=1).values
    ids = df2[cols_id].values

    sims = []

    for i, vec in enumerate(X):
        sim = cosine_sim(target_vec, vec)
        sims.append((ids[i], sim))

    # sort giảm dần
    sims.sort(key=lambda x: x[1], reverse=True)

    return sims

In [13]:
# lấy vector của user bất kỳ
target_vec = df2[df2["uid"] == 4].drop("uid", axis=1).values[0]

result_from_user_coll= get_similarity(df2, target_vec, "uid")

for uid, sim in result_from_user_coll[1:5]:
    print(uid, sim)

24 0.6666666666666667
15 0.33333333333333337
22 0.33333333333333337
1 0

In [14]:
query = "select * from case_based;"
mycursor.execute(query)

df_case_based = mycursor.fetchall()

print(df_case_based)
mydb.commit()

[(1, 'power-pop', '1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (2, 'ska,dance,soul', '5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,246dkjvS1zLTtiykXe5h60,3TVXtAsR1Inumwj472S9r4,3Nrfpe0tUJi4K4DXYWgMUX,06HL4z0CvFAxyc27GXpf02', 0.0), (3, 'cantopop', '7dGJo4pcD2V6oG8kP0tJRR,4q3ewBCX7sLwd24euuV69X', 0.0), (4, 'tango,piano,new-age,sleep', '1Xyo4u8uXC1ZmMpatF05PJ,6KImCVD70vtIoJWnq6nGn3,1uNFoZAHBGtllmzznpCI3s,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,3Nrfpe0tUJi4K4DXYWgMUX,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (5, 'opera,party,piano,cantopop,samba', '1Xyo4u8uXC1ZmMpatF05PJ,1mcTU81TzQhprhouKaTkpq,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (6, 'sleep,detroit-techno', '4q3ewBCX7sLwd24euuV69X,1mcTU81TzQhprhouKaTkpq,3TVXtAsR1Inumwj472S9r4,6KImCVD70vtIoJWnq6nGn3,1Xyo4u8uXC1ZmMpatF05PJ,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,3Nrfpe0tUJi4K4DXYWgMUX,246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (7, 'singer-songwriter,sertanejo', '1mcTU81TzQhprhouKaTkpq,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (8, 'deep-house', '1uNFoZAHBGtllmzznpCI3s,7dGJo4pcD2V6oG8kP0tJRR,1mcTU81TzQhprhouKaTkpq,5K4W6rqBFWDnAN6FQUkS6x,3Nrfpe0tUJi4K4DXYWgMUX,6eUKZXaKkcviH0Ku9w2n3V,1Xyo4u8uXC1ZmMpatF05PJ,6KImCVD70vtIoJWnq6nGn3,246dkjvS1zLTtiykXe5h60,4q3ewBCX7sLwd24euuV69X', 0.0), (9, 'acoustic,metal,funk,progressive-house,blues,trip-hop,rock', '1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V,6KImCVD70vtIoJWnq6nGn3', 0.0), (10, 'trip-hop,afrobeat,dancehall,chicago-house', '1Xyo4u8uXC1ZmMpatF05PJ,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,4q3ewBCX7sLwd24euuV69X,246dkjvS1zLTtiykXe5h60,1mcTU81TzQhprhouKaTkpq,7dGJo4pcD2V6oG8kP0tJRR,3TVXtAsR1Inumwj472S9r4,6eUKZXaKkcviH0Ku9w2n3V,6KImCVD70vtIoJWnq6nGn3', 0.0), (11, 'black-metal,dance,punk-rock,german,rock', '1uNFoZAHBGtllmzznpCI3s,3TVXtAsR1Inumwj472S9r4,5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,1Xyo4u8uXC1ZmMpatF05PJ,3Nrfpe0tUJi4K4DXYWgMUX,06HL4z0CvFAxyc27GXpf02,1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60', 0.0), (12, 'progressive-house,garage,trip-hop', '1uNFoZAHBGtllmzznpCI3s,06HL4z0CvFAxyc27GXpf02,4q3ewBCX7sLwd24euuV69X,7dGJo4pcD2V6oG8kP0tJRR,6KImCVD70vtIoJWnq6nGn3', 0.0), (13, 'swedish,disco', '7dGJo4pcD2V6oG8kP0tJRR,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (14, 'groove,club', '6eUKZXaKkcviH0Ku9w2n3V,06HL4z0CvFAxyc27GXpf02,5K4W6rqBFWDnAN6FQUkS6x,6KImCVD70vtIoJWnq6nGn3,1uNFoZAHBGtllmzznpCI3s,246dkjvS1zLTtiykXe5h60,1Xyo4u8uXC1ZmMpatF05PJ,3Nrfpe0tUJi4K4DXYWgMUX,1mcTU81TzQhprhouKaTkpq,3TVXtAsR1Inumwj472S9r4', 0.0), (15, 'groove,chicago-house,metal', '6eUKZXaKkcviH0Ku9w2n3V,1uNFoZAHBGtllmzznpCI3s', 0.0), (16, 'detroit-techno,punk-rock,emo,french,swedish', '246dkjvS1zLTtiykXe5h60,3TVXtAsR1Inumwj472S9r4,3Nrfpe0tUJi4K4DXYWgMUX,1mcTU81TzQhprhouKaTkpq,7dGJo4pcD2V6oG8kP0tJRR,6KImCVD70vtIoJWnq6nGn3,5K4W6rqBFWDnAN6FQUkS6x,4q3ewBCX7sLwd24euuV69X,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (17, 'acoustic,edm', '3TVXtAsR1Inumwj472S9r4,4q3ewBCX7sLwd24euuV69X,6eUKZXaKkcviH0Ku9w2n3V,1uNFoZAHBGtllmzznpCI3s', 0.0), (18, 'psych-rock,tango,black-metal,disco,country', '7dGJo4pcD2V6oG8kP0tJRR,6eUKZXaKkcviH0Ku9w2n3V,246dkjvS1zLTtiykXe5h60,1uNFoZAHBGtllmzznpCI3s', 0.0), (19, 'gospel', '246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V,7dGJo4pcD2V6oG8kP0tJRR,1mcTU81TzQhprhouKaTkpq,4q3ewBCX7sLwd24euuV69X,3TVXtAsR1Inumwj472S9r4,5K4W6rqBFWDnAN6FQUkS6x,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (20, 'goth,garage,french,death-metal,guitar,minimal-techno,detroit-techno', '246dkjvS1zLTtiykXe5h60', 0.0), (21, 'alt-rock,k-pop,show-tunes,garage,blues,soul,tango', '06HL4z0CvFAxyc27GXpf02,1Xyo4u8uXC1ZmMpatF05PJ,4q3ewBCX7sLwd24euuV69X,1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60,7dGJo4pcD2V6oG8kP0tJRR,6KImCVD70vtIoJWnq6nGn3,5K4W6rqBFWDnAN6FQUkS6x', 0.0), (22, 'indian,romance,metal,piano,heavy-metal,cantopop', '06HL4z0CvFAxyc27GXpf02,1Xyo4u8uXC1ZmMpatF05PJ,3Nrfpe0tUJi4K4DXYWgMUX,3TVXtAsR1Inumwj472S9r4,7dGJo4pcD2V6oG8kP0tJRR,1uNFoZAHBGtllmzznpCI3s,1mcTU81TzQhprhouKaTkpq,5K4W6rqBFWDnAN6FQUkS6x', 0.0), (23, 'goth,hardstyle,sertanejo,blues,dub', '3TVXtAsR1Inumwj472S9r4', 0.0), (24, 'dub,power-pop,tango', '1uNFoZAHBGtllmzznpCI3s,5K4W6rqBFWDnAN6FQUkS6x,7dGJo4pcD2V6oG8kP0tJRR,6eUKZXaKkcviH0Ku9w2n3V,6KImCVD70vtIoJWnq6nGn3,3TVXtAsR1Inumwj472S9r4,4q3ewBCX7sLwd24euuV69X', 0.0), (25, 'death-metal,hardcore,indian,soul,club,breakbeat,funk', '1Xyo4u8uXC1ZmMpatF05PJ,06HL4z0CvFAxyc27GXpf02,1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V,1uNFoZAHBGtllmzznpCI3s', 0.0), (26, 'sleep', '1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60,5K4W6rqBFWDnAN6FQUkS6x,6KImCVD70vtIoJWnq6nGn3,4q3ewBCX7sLwd24euuV69X,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (27, 'industrial,singer-songwriter', '3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (28, 'ska,heavy-metal,dub,groove,progressive-house,punk,deep-house', '3Nrfpe0tUJi4K4DXYWgMUX,1mcTU81TzQhprhouKaTkpq', 0.0), (29, 'sleep,dancehall', '1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (30, 'cantopop,show-tunes,alt-rock,edm,metal,forro', '1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (31, 'metalcore,hard-rock,opera', '1uNFoZAHBGtllmzznpCI3s,1Xyo4u8uXC1ZmMpatF05PJ,3TVXtAsR1Inumwj472S9r4,6KImCVD70vtIoJWnq6nGn3,3Nrfpe0tUJi4K4DXYWgMUX,4q3ewBCX7sLwd24euuV69X,06HL4z0CvFAxyc27GXpf02,6eUKZXaKkcviH0Ku9w2n3V,7dGJo4pcD2V6oG8kP0tJRR,246dkjvS1zLTtiykXe5h60', 0.0), (32, 'samba', '1uNFoZAHBGtllmzznpCI3s,246dkjvS1zLTtiykXe5h60,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,3Nrfpe0tUJi4K4DXYWgMUX,6KImCVD70vtIoJWnq6nGn3,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (33, 'death-metal,rock-n-roll', '1mcTU81TzQhprhouKaTkpq,6KImCVD70vtIoJWnq6nGn3,06HL4z0CvFAxyc27GXpf02,3TVXtAsR1Inumwj472S9r4,3Nrfpe0tUJi4K4DXYWgMUX,7dGJo4pcD2V6oG8kP0tJRR,246dkjvS1zLTtiykXe5h60,1uNFoZAHBGtllmzznpCI3s,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (34, 'punk,sertanejo,opera,black-metal,breakbeat,chill', '1mcTU81TzQhprhouKaTkpq', 0.0), (35, 'heavy-metal', '6eUKZXaKkcviH0Ku9w2n3V,1mcTU81TzQhprhouKaTkpq', 0.0), (36, 'ska', '3TVXtAsR1Inumwj472S9r4', 0.0), (37, 'heavy-metal,blues,industrial,german', '246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,4q3ewBCX7sLwd24euuV69X,1mcTU81TzQhprhouKaTkpq', 0.0), (38, 'rock-n-roll', '7dGJo4pcD2V6oG8kP0tJRR,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (39, 'minimal-techno,deep-house,classical,cantopop,black-metal,emo,forro', '1uNFoZAHBGtllmzznpCI3s,3Nrfpe0tUJi4K4DXYWgMUX,4q3ewBCX7sLwd24euuV69X,5K4W6rqBFWDnAN6FQUkS6x,1Xyo4u8uXC1ZmMpatF05PJ,7dGJo4pcD2V6oG8kP0tJRR,06HL4z0CvFAxyc27GXpf02,3TVXtAsR1Inumwj472S9r4,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (40, 'heavy-metal,new-age', '6eUKZXaKkcviH0Ku9w2n3V,1mcTU81TzQhprhouKaTkpq,3TVXtAsR1Inumwj472S9r4', 0.0), (41, 'hip-hop', '246dkjvS1zLTtiykXe5h60,3Nrfpe0tUJi4K4DXYWgMUX,6eUKZXaKkcviH0Ku9w2n3V,3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq,7dGJo4pcD2V6oG8kP0tJRR,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02', 0.0), (42, 'hip-hop', '7dGJo4pcD2V6oG8kP0tJRR,3TVXtAsR1Inumwj472S9r4,5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,1uNFoZAHBGtllmzznpCI3s,4q3ewBCX7sLwd24euuV69X,06HL4z0CvFAxyc27GXpf02,6KImCVD70vtIoJWnq6nGn3,1mcTU81TzQhprhouKaTkpq', 0.0), (43, 'garage,pop,hip-hop,piano,hard-rock,ska,punk-rock', '4q3ewBCX7sLwd24euuV69X', 0.0), (44, 'indie-pop,grindcore,k-pop,french', '3TVXtAsR1Inumwj472S9r4,1Xyo4u8uXC1ZmMpatF05PJ,7dGJo4pcD2V6oG8kP0tJRR,6KImCVD70vtIoJWnq6nGn3,3Nrfpe0tUJi4K4DXYWgMUX,06HL4z0CvFAxyc27GXpf02,5K4W6rqBFWDnAN6FQUkS6x,1uNFoZAHBGtllmzznpCI3s', 0.0), (45, 'k-pop,french,death-metal,ambient,hardstyle', '5K4W6rqBFWDnAN6FQUkS6x,1mcTU81TzQhprhouKaTkpq,6KImCVD70vtIoJWnq6nGn3,1uNFoZAHBGtllmzznpCI3s,246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V,1Xyo4u8uXC1ZmMpatF05PJ,3TVXtAsR1Inumwj472S9r4,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (46, 'show-tunes,progressive-house', '3Nrfpe0tUJi4K4DXYWgMUX,3TVXtAsR1Inumwj472S9r4,5K4W6rqBFWDnAN6FQUkS6x,1uNFoZAHBGtllmzznpCI3s,4q3ewBCX7sLwd24euuV69X,1mcTU81TzQhprhouKaTkpq,7dGJo4pcD2V6oG8kP0tJRR,1Xyo4u8uXC1ZmMpatF05PJ,06HL4z0CvFAxyc27GXpf02', 0.0), (47, 'forro,spanish,hip-hop,heavy-metal', '246dkjvS1zLTtiykXe5h60,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (48, 'sad,guitar', '6eUKZXaKkcviH0Ku9w2n3V,06HL4z0CvFAxyc27GXpf02,3TVXtAsR1Inumwj472S9r4,5K4W6rqBFWDnAN6FQUkS6x', 0.0), (49, 'edm,party,heavy-metal,punk-rock,trance,guitar,drum-and-bass', '7dGJo4pcD2V6oG8kP0tJRR', 0.0), (50, 'jazz', '7dGJo4pcD2V6oG8kP0tJRR,3Nrfpe0tUJi4K4DXYWgMUX,1uNFoZAHBGtllmzznpCI3s', 0.0), (51, 'indie-pop,electro,chill,indian,new-age,opera,detroit-techno', '1Xyo4u8uXC1ZmMpatF05PJ,4q3ewBCX7sLwd24euuV69X,6eUKZXaKkcviH0Ku9w2n3V,246dkjvS1zLTtiykXe5h60', 0.0), (52, 'heavy-metal,deep-house,indie-pop,piano,metal,swedish,samba', '6KImCVD70vtIoJWnq6nGn3,7dGJo4pcD2V6oG8kP0tJRR,3Nrfpe0tUJi4K4DXYWgMUX,6eUKZXaKkcviH0Ku9w2n3V,1Xyo4u8uXC1ZmMpatF05PJ,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq', 0.0), (53, 'disco,indian,power-pop,punk', '6KImCVD70vtIoJWnq6nGn3,1uNFoZAHBGtllmzznpCI3s,06HL4z0CvFAxyc27GXpf02,246dkjvS1zLTtiykXe5h60', 0.0), (54, 'breakbeat,metalcore,psych-rock,opera,goth,punk-rock', '3TVXtAsR1Inumwj472S9r4,7dGJo4pcD2V6oG8kP0tJRR,1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V,1uNFoZAHBGtllmzznpCI3s,4q3ewBCX7sLwd24euuV69X,1mcTU81TzQhprhouKaTkpq,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (55, 'trance,pop', '1uNFoZAHBGtllmzznpCI3s,1mcTU81TzQhprhouKaTkpq,5K4W6rqBFWDnAN6FQUkS6x,3Nrfpe0tUJi4K4DXYWgMUX,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (56, 'punk,salsa,trance,club,death-metal', '1Xyo4u8uXC1ZmMpatF05PJ,1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60,3Nrfpe0tUJi4K4DXYWgMUX,5K4W6rqBFWDnAN6FQUkS6x', 0.0), (57, 'progressive-house', '3Nrfpe0tUJi4K4DXYWgMUX,1mcTU81TzQhprhouKaTkpq,06HL4z0CvFAxyc27GXpf02', 0.0), (58, 'samba,electronic,show-tunes,alt-rock,spanish,black-metal', '3Nrfpe0tUJi4K4DXYWgMUX,1mcTU81TzQhprhouKaTkpq,6eUKZXaKkcviH0Ku9w2n3V,3TVXtAsR1Inumwj472S9r4,4q3ewBCX7sLwd24euuV69X', 0.0), (59, 'hard-rock,indie-pop,grindcore', '4q3ewBCX7sLwd24euuV69X,6eUKZXaKkcviH0Ku9w2n3V,3TVXtAsR1Inumwj472S9r4,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (60, 'swedish,trance,show-tunes,ambient,emo,blues,hardcore', '246dkjvS1zLTtiykXe5h60,7dGJo4pcD2V6oG8kP0tJRR,06HL4z0CvFAxyc27GXpf02,6KImCVD70vtIoJWnq6nGn3,1Xyo4u8uXC1ZmMpatF05PJ,3TVXtAsR1Inumwj472S9r4,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (61, 'black-metal,spanish,folk,trip-hop,groove,guitar', '6KImCVD70vtIoJWnq6nGn3,3Nrfpe0tUJi4K4DXYWgMUX,5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,1Xyo4u8uXC1ZmMpatF05PJ,06HL4z0CvFAxyc27GXpf02,1mcTU81TzQhprhouKaTkpq,3TVXtAsR1Inumwj472S9r4,246dkjvS1zLTtiykXe5h60,4q3ewBCX7sLwd24euuV69X', 0.0), (62, 'songwriter', '7dGJo4pcD2V6oG8kP0tJRR,3TVXtAsR1Inumwj472S9r4,4q3ewBCX7sLwd24euuV69X,6KImCVD70vtIoJWnq6nGn3,246dkjvS1zLTtiykXe5h60,1mcTU81TzQhprhouKaTkpq,5K4W6rqBFWDnAN6FQUkS6x,1uNFoZAHBGtllmzznpCI3s,06HL4z0CvFAxyc27GXpf02,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (63, 'ska,pop-film', '6KImCVD70vtIoJWnq6nGn3', 0.0), (64, 'cantopop,metalcore,hardstyle,show-tunes,songwriter,pop,club', '4q3ewBCX7sLwd24euuV69X,5K4W6rqBFWDnAN6FQUkS6x,3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq,06HL4z0CvFAxyc27GXpf02,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (65, 'rock,country', '1uNFoZAHBGtllmzznpCI3s,6KImCVD70vtIoJWnq6nGn3,06HL4z0CvFAxyc27GXpf02', 0.0), (66, 'death-metal,punk-rock', '5K4W6rqBFWDnAN6FQUkS6x', 0.0), (67, 'afrobeat,hip-hop,trip-hop,singer-songwriter', '7dGJo4pcD2V6oG8kP0tJRR,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (68, 'sertanejo,jazz,sleep,breakbeat,indie-pop,singer-songwriter,emo', '06HL4z0CvFAxyc27GXpf02', 0.0), (69, 'pop', '6eUKZXaKkcviH0Ku9w2n3V', 0.0), (70, 'forro,show-tunes,chill', '1uNFoZAHBGtllmzznpCI3s', 0.0), (71, 'psych-rock,grindcore,industrial', '5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,6KImCVD70vtIoJWnq6nGn3,1mcTU81TzQhprhouKaTkpq,3Nrfpe0tUJi4K4DXYWgMUX,1uNFoZAHBGtllmzznpCI3s', 0.0), (72, 'chill,songwriter,romance,pop', '4q3ewBCX7sLwd24euuV69X,6KImCVD70vtIoJWnq6nGn3,246dkjvS1zLTtiykXe5h60,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (73, 'party,singer-songwriter,ska,chill,spanish', '246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V,4q3ewBCX7sLwd24euuV69X,5K4W6rqBFWDnAN6FQUkS6x,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (74, 'indie-pop,opera,hardcore,techno,electronic', '3TVXtAsR1Inumwj472S9r4', 0.0), (75, 'drum-and-bass', '6eUKZXaKkcviH0Ku9w2n3V,246dkjvS1zLTtiykXe5h60,5K4W6rqBFWDnAN6FQUkS6x', 0.0), (76, 'edm,afrobeat,punk-rock,industrial,hardcore', '1uNFoZAHBGtllmzznpCI3s,1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60,4q3ewBCX7sLwd24euuV69X,06HL4z0CvFAxyc27GXpf02,1Xyo4u8uXC1ZmMpatF05PJ,7dGJo4pcD2V6oG8kP0tJRR,5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,3TVXtAsR1Inumwj472S9r4', 0.0), (77, 'black-metal,drum-and-bass', '246dkjvS1zLTtiykXe5h60,3Nrfpe0tUJi4K4DXYWgMUX,1mcTU81TzQhprhouKaTkpq,4q3ewBCX7sLwd24euuV69X', 0.0), (78, 'punk-rock,house,grindcore', '246dkjvS1zLTtiykXe5h60,7dGJo4pcD2V6oG8kP0tJRR,3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq,1uNFoZAHBGtllmzznpCI3s,3Nrfpe0tUJi4K4DXYWgMUX,4q3ewBCX7sLwd24euuV69X', 0.0), (79, 'minimal-techno,acoustic,club,disco,techno', '6eUKZXaKkcviH0Ku9w2n3V,4q3ewBCX7sLwd24euuV69X,246dkjvS1zLTtiykXe5h60,06HL4z0CvFAxyc27GXpf02,7dGJo4pcD2V6oG8kP0tJRR,3TVXtAsR1Inumwj472S9r4,1Xyo4u8uXC1ZmMpatF05PJ,6KImCVD70vtIoJWnq6nGn3,1mcTU81TzQhprhouKaTkpq', 0.0), (80, 'edm,blues,hardstyle,classical', '1mcTU81TzQhprhouKaTkpq,3TVXtAsR1Inumwj472S9r4,6KImCVD70vtIoJWnq6nGn3,7dGJo4pcD2V6oG8kP0tJRR,4q3ewBCX7sLwd24euuV69X,3Nrfpe0tUJi4K4DXYWgMUX,1Xyo4u8uXC1ZmMpatF05PJ,1uNFoZAHBGtllmzznpCI3s,06HL4z0CvFAxyc27GXpf02', 0.0), (81, 'hardcore', '06HL4z0CvFAxyc27GXpf02,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (82, 'emo,country,classical,heavy-metal', '1uNFoZAHBGtllmzznpCI3s,6eUKZXaKkcviH0Ku9w2n3V,3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq,246dkjvS1zLTtiykXe5h60,4q3ewBCX7sLwd24euuV69X,1Xyo4u8uXC1ZmMpatF05PJ,3Nrfpe0tUJi4K4DXYWgMUX,6KImCVD70vtIoJWnq6nGn3', 0.0), (83, 'party,punk-rock,grindcore,club,country', '6KImCVD70vtIoJWnq6nGn3,06HL4z0CvFAxyc27GXpf02,1mcTU81TzQhprhouKaTkpq,7dGJo4pcD2V6oG8kP0tJRR,3TVXtAsR1Inumwj472S9r4,1Xyo4u8uXC1ZmMpatF05PJ,246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V', 0.0), (84, 'dancehall,dubstep', '4q3ewBCX7sLwd24euuV69X,246dkjvS1zLTtiykXe5h60,06HL4z0CvFAxyc27GXpf02,1uNFoZAHBGtllmzznpCI3s,3TVXtAsR1Inumwj472S9r4,6KImCVD70vtIoJWnq6nGn3,5K4W6rqBFWDnAN6FQUkS6x,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (85, 'metalcore', '6eUKZXaKkcviH0Ku9w2n3V,7dGJo4pcD2V6oG8kP0tJRR,5K4W6rqBFWDnAN6FQUkS6x,6KImCVD70vtIoJWnq6nGn3,3Nrfpe0tUJi4K4DXYWgMUX,1Xyo4u8uXC1ZmMpatF05PJ,1uNFoZAHBGtllmzznpCI3s,246dkjvS1zLTtiykXe5h60', 0.0), (86, 'indian,heavy-metal,electronic,sertanejo,industrial', '06HL4z0CvFAxyc27GXpf02,1mcTU81TzQhprhouKaTkpq,6KImCVD70vtIoJWnq6nGn3,5K4W6rqBFWDnAN6FQUkS6x,7dGJo4pcD2V6oG8kP0tJRR,1uNFoZAHBGtllmzznpCI3s,3Nrfpe0tUJi4K4DXYWgMUX,4q3ewBCX7sLwd24euuV69X,6eUKZXaKkcviH0Ku9w2n3V,246dkjvS1zLTtiykXe5h60', 0.0), (87, 'metal,salsa,singer-songwriter,punk-rock,punk,soul,ambient', '246dkjvS1zLTtiykXe5h60,7dGJo4pcD2V6oG8kP0tJRR,4q3ewBCX7sLwd24euuV69X,6KImCVD70vtIoJWnq6nGn3,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,6eUKZXaKkcviH0Ku9w2n3V,1uNFoZAHBGtllmzznpCI3s,3TVXtAsR1Inumwj472S9r4,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (88, 'romance,chicago-house,hardcore', '4q3ewBCX7sLwd24euuV69X,246dkjvS1zLTtiykXe5h60,1uNFoZAHBGtllmzznpCI3s,3Nrfpe0tUJi4K4DXYWgMUX,7dGJo4pcD2V6oG8kP0tJRR,06HL4z0CvFAxyc27GXpf02,1Xyo4u8uXC1ZmMpatF05PJ,5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,1mcTU81TzQhprhouKaTkpq', 0.0), (89, 'french,death-metal,sertanejo,progressive-house,edm', '3TVXtAsR1Inumwj472S9r4,1Xyo4u8uXC1ZmMpatF05PJ,1mcTU81TzQhprhouKaTkpq,06HL4z0CvFAxyc27GXpf02,7dGJo4pcD2V6oG8kP0tJRR,3Nrfpe0tUJi4K4DXYWgMUX,5K4W6rqBFWDnAN6FQUkS6x,246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V,6KImCVD70vtIoJWnq6nGn3', 0.0), (90, 'industrial,acoustic,disco,guitar', '3TVXtAsR1Inumwj472S9r4,6KImCVD70vtIoJWnq6nGn3,246dkjvS1zLTtiykXe5h60,06HL4z0CvFAxyc27GXpf02,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (91, 'club,rock,cantopop,hardstyle,punk,funk', '7dGJo4pcD2V6oG8kP0tJRR,4q3ewBCX7sLwd24euuV69X,06HL4z0CvFAxyc27GXpf02,6KImCVD70vtIoJWnq6nGn3,6eUKZXaKkcviH0Ku9w2n3V,3Nrfpe0tUJi4K4DXYWgMUX,5K4W6rqBFWDnAN6FQUkS6x,1Xyo4u8uXC1ZmMpatF05PJ,1mcTU81TzQhprhouKaTkpq', 0.0), (92, 'dub,sad,indie-pop,deep-house,emo', '1Xyo4u8uXC1ZmMpatF05PJ,7dGJo4pcD2V6oG8kP0tJRR,3Nrfpe0tUJi4K4DXYWgMUX,4q3ewBCX7sLwd24euuV69X,246dkjvS1zLTtiykXe5h60,6eUKZXaKkcviH0Ku9w2n3V,06HL4z0CvFAxyc27GXpf02', 0.0), (93, 'german,french', '3Nrfpe0tUJi4K4DXYWgMUX,3TVXtAsR1Inumwj472S9r4,1uNFoZAHBGtllmzznpCI3s,6KImCVD70vtIoJWnq6nGn3,06HL4z0CvFAxyc27GXpf02', 0.0), (94, 'industrial,country', '3TVXtAsR1Inumwj472S9r4,1uNFoZAHBGtllmzznpCI3s,3Nrfpe0tUJi4K4DXYWgMUX,1mcTU81TzQhprhouKaTkpq,5K4W6rqBFWDnAN6FQUkS6x,6KImCVD70vtIoJWnq6nGn3,6eUKZXaKkcviH0Ku9w2n3V,7dGJo4pcD2V6oG8kP0tJRR,4q3ewBCX7sLwd24euuV69X', 0.0), (95, 'techno,funk,jazz,pop-film,opera', '3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (96, 'chicago-house,drum-and-bass,punk,detroit-techno,songwriter', '1Xyo4u8uXC1ZmMpatF05PJ,1mcTU81TzQhprhouKaTkpq,7dGJo4pcD2V6oG8kP0tJRR,6KImCVD70vtIoJWnq6nGn3,6eUKZXaKkcviH0Ku9w2n3V,4q3ewBCX7sLwd24euuV69X,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (97, 'piano,singer-songwriter,show-tunes,power-pop,country,indie-pop', '06HL4z0CvFAxyc27GXpf02,6eUKZXaKkcviH0Ku9w2n3V,4q3ewBCX7sLwd24euuV69X,246dkjvS1zLTtiykXe5h60,6KImCVD70vtIoJWnq6nGn3', 0.0), (98, 'salsa,hip-hop,electronic,french,rock,hardstyle', '06HL4z0CvFAxyc27GXpf02,7dGJo4pcD2V6oG8kP0tJRR,5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,3Nrfpe0tUJi4K4DXYWgMUX,1Xyo4u8uXC1ZmMpatF05PJ,4q3ewBCX7sLwd24euuV69X,3TVXtAsR1Inumwj472S9r4', 0.0), (99, 'sad,acoustic,indie-pop,classical,heavy-metal,funk,dubstep', '7dGJo4pcD2V6oG8kP0tJRR,1uNFoZAHBGtllmzznpCI3s,5K4W6rqBFWDnAN6FQUkS6x,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (100, 'pop,pop-film', '1mcTU81TzQhprhouKaTkpq,6eUKZXaKkcviH0Ku9w2n3V,7dGJo4pcD2V6oG8kP0tJRR,3TVXtAsR1Inumwj472S9r4,6KImCVD70vtIoJWnq6nGn3,246dkjvS1zLTtiykXe5h60,5K4W6rqBFWDnAN6FQUkS6x,06HL4z0CvFAxyc27GXpf02,3Nrfpe0tUJi4K4DXYWgMUX', 0.0), (101, 'new-age,sad,classical', '1mcTU81TzQhprhouKaTkpq,3TVXtAsR1Inumwj472S9r4', 0.0), (102, 'dubstep,rock-n-roll,dance,chill,drum-and-bass,guitar', '1uNFoZAHBGtllmzznpCI3s,246dkjvS1zLTtiykXe5h60,06HL4z0CvFAxyc27GXpf02', 0.0), (103, 'disco,breakbeat', '5K4W6rqBFWDnAN6FQUkS6x,1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V,3Nrfpe0tUJi4K4DXYWgMUX,7dGJo4pcD2V6oG8kP0tJRR,06HL4z0CvFAxyc27GXpf02,3TVXtAsR1Inumwj472S9r4', 0.0), (104, 'dubstep,heavy-metal,romance', '1uNFoZAHBGtllmzznpCI3s,7dGJo4pcD2V6oG8kP0tJRR,1Xyo4u8uXC1ZmMpatF05PJ,4q3ewBCX7sLwd24euuV69X,6KImCVD70vtIoJWnq6nGn3,1mcTU81TzQhprhouKaTkpq,3TVXtAsR1Inumwj472S9r4,06HL4z0CvFAxyc27GXpf02,5K4W6rqBFWDnAN6FQUkS6x', 0.0), (105, 'singer-songwriter', '06HL4z0CvFAxyc27GXpf02,246dkjvS1zLTtiykXe5h60,1Xyo4u8uXC1ZmMpatF05PJ,3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq,3Nrfpe0tUJi4K4DXYWgMUX,1uNFoZAHBGtllmzznpCI3s,6KImCVD70vtIoJWnq6nGn3', 0.0), (106, 'breakbeat,indian,forro,sleep,trance,dancehall,show-tunes', '3TVXtAsR1Inumwj472S9r4', 0.0), (107, 'progressive-house,garage,club,hardstyle,industrial,funk', '6KImCVD70vtIoJWnq6nGn3,06HL4z0CvFAxyc27GXpf02,1mcTU81TzQhprhouKaTkpq,1Xyo4u8uXC1ZmMpatF05PJ', 0.0), (108, 'minimal-techno,salsa,swedish,opera', '4q3ewBCX7sLwd24euuV69X,6KImCVD70vtIoJWnq6nGn3,1uNFoZAHBGtllmzznpCI3s,06HL4z0CvFAxyc27GXpf02', 0.0), (109, 'indie-pop,pop-film,rock-n-roll,minimal-techno,house', '5K4W6rqBFWDnAN6FQUkS6x,3TVXtAsR1Inumwj472S9r4,1mcTU81TzQhprhouKaTkpq,1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (110, 'punk-rock,guitar', '3Nrfpe0tUJi4K4DXYWgMUX,246dkjvS1zLTtiykXe5h60,4q3ewBCX7sLwd24euuV69X', 0.0), (111, 'sertanejo,country,house,gospel,french', '4q3ewBCX7sLwd24euuV69X,246dkjvS1zLTtiykXe5h60,5K4W6rqBFWDnAN6FQUkS6x,3Nrfpe0tUJi4K4DXYWgMUX,06HL4z0CvFAxyc27GXpf02,1mcTU81TzQhprhouKaTkpq', 0.0), (112, 'german,party,ska,hard-rock,minimal-techno,metalcore', '4q3ewBCX7sLwd24euuV69X', 0.0), (113, 'forro,chill,pop,samba', '06HL4z0CvFAxyc27GXpf02,1uNFoZAHBGtllmzznpCI3s,3TVXtAsR1Inumwj472S9r4,3Nrfpe0tUJi4K4DXYWgMUX,5K4W6rqBFWDnAN6FQUkS6x,246dkjvS1zLTtiykXe5h60', 0.0), (114, 'metalcore,ambient', '4q3ewBCX7sLwd24euuV69X,1Xyo4u8uXC1ZmMpatF05PJ,3TVXtAsR1Inumwj472S9r4,3Nrfpe0tUJi4K4DXYWgMUX,7dGJo4pcD2V6oG8kP0tJRR', 0.0), (115, 'hardstyle,trip-hop,funk,garage,emo,death-metal', '246dkjvS1zLTtiykXe5h60,6KImCVD70vtIoJWnq6nGn3,3Nrfpe0tUJi4K4DXYWgMUX,3TVXtAsR1Inumwj472S9r4', 0.0), (116

In [15]:
import pandas as pd

df_cb = pd.DataFrame(df_case_based, columns=[
    "cbid", "genres", "artist_id", "score"
])
df_cb.head(10)

,cbid,genres,artist_id,score
0,1,power-pop,"1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V",0.0
1,2,"ska,dance,soul","5K4W6rqBFWDnAN6FQUkS6x,6eUKZXaKkcviH0Ku9w2n3V,...",0.0
2,3,cantopop,"7dGJo4pcD2V6oG8kP0tJRR,4q3ewBCX7sLwd24euuV69X",0.0
3,4,"tango,piano,new-age,sleep","1Xyo4u8uXC1ZmMpatF05PJ,6KImCVD70vtIoJWnq6nGn3,...",0.0
4,5,"opera,party,piano,cantopop,samba","1Xyo4u8uXC1ZmMpatF05PJ,1mcTU81TzQhprhouKaTkpq,...",0.0
5,6,"sleep,detroit-techno","4q3ewBCX7sLwd24euuV69X,1mcTU81TzQhprhouKaTkpq,...",0.0
6,7,"singer-songwriter,sertanejo","1mcTU81TzQhprhouKaTkpq,3Nrfpe0tUJi4K4DXYWgMUX",0.0
7,8,deep-house,"1uNFoZAHBGtllmzznpCI3s,7dGJo4pcD2V6oG8kP0tJRR,...",0.0
8,9,"acoustic,metal,funk,progressive-house,blues,tr...","1Xyo4u8uXC1ZmMpatF05PJ,6eUKZXaKkcviH0Ku9w2n3V,...",0.0
9,10,"trip-hop,afrobeat,dancehall,chicago-house","1Xyo4u8uXC1ZmMpatF05PJ,5K4W6rqBFWDnAN6FQUkS6x,...",0.0

In [16]:
def case_based_genre_matrix(df1):
    # chỉ lấy 2 cột cần
    df = df1[["cbid", "genres"]].copy()

    # xử lý null / rỗng
    df["genres"] = df["genres"].fillna("")
    
    # tách list genre
    df["genres"] = df["genres"].apply(
        lambda x: [g.strip() for g in x.split(",") if g.strip()]
    )

    # explode
    df = df.explode("genres")

    # tạo one-hot
    df = pd.get_dummies(df, columns=["genres"])

    # group lại theo user
    df = df.groupby("cbid").max().reset_index()

    # đảm bảo đủ tất cả genre
    for g in GENRES:
        col = f"genres_{g}"
        if col not in df.columns:
            df[col] = 0

    # rename cho gọn
    df.columns = [c.replace("genres_", "") for c in df.columns]

    # sắp xếp cột
    df = df[["cbid"] + GENRES]

    return df

dfcb = case_based_genre_matrix(df_cb)
dfcb = dfcb.astype(int)
print(dfcb.head())

   cbid  acoustic  afrobeat  alt-rock  ambient  black-metal  blues  breakbeat  \
0     1         0         0         0        0            0      0          0
1     2         0         0         0        0            0      0          0
2     3         0         0         0        0            0      0          0
3     4         0         0         0        0            0      0          0
4     5         0         0         0        0            0      0          0

   cantopop  chicago-house  ...  ska  sleep  songwriter  soul  spanish  \
0         0              0  ...    0      0           0     0        0
1         0              0  ...    1      0           0     1        0
2         1              0  ...    0      0           0     0        0
3         0              0  ...    0      1           0     0        0
4         1              0  ...    0      0           0     0        0

   swedish  tango  techno  trance  trip-hop
0        0      0       0       0         0
1        0      0       0       0         0
2        0      0       0       0         0
3        0      1       0       0         0
4        0      0       0       0         0

[5 rows x 83 columns]

In [17]:
# lấy vector của user bất kỳ
target_vec = df2[df2["uid"] == 15].drop("uid", axis=1).values[0]

result_from_case_based = get_similarity(dfcb, target_vec, "cbid")

for cbid, sim in result_from_case_based[:10]:
    print(cbid, sim)

149 0.5773502691896258
208 0.5773502691896258
79 0.5163977794943222
288 0.47140452079103173
20 0.4364357804719848
171 0.4364357804719848
6 0.40824829046386296
144 0.40824829046386296
267 0.40824829046386296
151 0.33333333333333337

In [18]:
# print(result_from_case_based)
dftmp = pd.DataFrame(result_from_case_based, columns=["cbid", "sim"])
dftmp = pd.merge(dftmp, df_cb, on="cbid")
dftmp.head()
# score_artist = []
# cnt = 0
# for i in range(len(dftmp)):
#     arr = dftmp.iloc[i]["artist_id"].split(",")
#     # print(dftmp.iloc[i]["sim"])
#     for j in arr:
#         # print(j)
#         if j not in score_artist:
#             score_artist.append(j)
#             cnt+=1
#         #     score_artist.append((j, float(0)))
#         # score_artist[j][1] += 0.7*float(dftmp.iloc[i]["sim"])

# print(cnt)
from collections import defaultdict

score_artist = defaultdict(float)
k = 0
for _, row in dftmp.iterrows():
    if k == 20:
        break
    sim = float(row["sim"])
    for artist in row["artist_id"].split(","):
        score_artist[artist] += 0.7 * sim

result = list(score_artist.items())

print(result)

[('7dGJo4pcD2V6oG8kP0tJRR', 3.1949385267989596), ('06HL4z0CvFAxyc27GXpf02', 4.589480901332517), ('1mcTU81TzQhprhouKaTkpq', 4.509603853977128), ('6eUKZXaKkcviH0Ku9w2n3V', 4.736647693650507), ('5K4W6rqBFWDnAN6FQUkS6x', 3.700609714298904), ('246dkjvS1zLTtiykXe5h60', 4.3984657628979935), ('1uNFoZAHBGtllmzznpCI3s', 3.173330978823879), ('1Xyo4u8uXC1ZmMpatF05PJ', 4.239682635937966), ('3Nrfpe0tUJi4K4DXYWgMUX', 3.410852308514666), ('3TVXtAsR1Inumwj472S9r4', 4.855439603816389), ('4q3ewBCX7sLwd24euuV69X', 4.308370115390316), ('6KImCVD70vtIoJWnq6nGn3', 4.46272476694318)]

In [20]:
dftmp1 = pd.DataFrame(result_from_user_coll, columns=["uid", "sim"])
dftmp1 = pd.merge(dftmp1, df1, on="uid")
dftmp1.head()

,uid,sim,favorite_genre,artist_id
0,4,1.000000,"tango, techno, trance","1Cs0zKBU1kc0i8ypK3B9ai, 2R21vXR83lH98kGeO99Y66..."
1,24,0.666667,"german, techno, trance","0Y5tJX1MQlPlqiwlOH1tJY, 2LRoIwlKmHjgvigdNGBHNo..."
2,15,0.333333,"techno, minimal-techno, detroit-techno","0du5cEVh5yTK9QJze8zA0C, 1McMsnEElThX1knmY4oliG..."
3,22,0.333333,"salsa, samba, tango","00FQb4jTyendYWaN8pK0wa, 3Nrfpe0tUJi4K4DXYWgMUX..."
4,1,0.000000,NaN,"0EmeFodog0BfCgMzAIvKQp, 3Nrfpe0tUJi4K4DXYWgMUX..."

In [21]:
from collections import defaultdict

# score_artist = defaultdict(float)
k = 0
for _, row in dftmp1.iterrows():
    if k == 20:
        break
    sim = float(row["sim"])
    if sim == 1:
        continue
    for artist in row["artist_id"].split(","):
        score_artist[artist] += 0.3 * sim

result = list(score_artist.items())

In [23]:
result = sorted(score_artist.items(), key=lambda x: x[1], reverse=True)
print(result)

[('3TVXtAsR1Inumwj472S9r4', 4.855439603816389), ('6eUKZXaKkcviH0Ku9w2n3V', 4.736647693650507), ('06HL4z0CvFAxyc27GXpf02', 4.589480901332517), ('1mcTU81TzQhprhouKaTkpq', 4.509603853977128), ('6KImCVD70vtIoJWnq6nGn3', 4.46272476694318), ('246dkjvS1zLTtiykXe5h60', 4.3984657628979935), ('4q3ewBCX7sLwd24euuV69X', 4.308370115390316), ('1Xyo4u8uXC1ZmMpatF05PJ', 4.239682635937966), ('5K4W6rqBFWDnAN6FQUkS6x', 3.700609714298904), ('3Nrfpe0tUJi4K4DXYWgMUX', 3.410852308514666), ('7dGJo4pcD2V6oG8kP0tJRR', 3.1949385267989596), ('1uNFoZAHBGtllmzznpCI3s', 3.173330978823879), (' 6l3HvQ5sa6mXTsMTB19rO5', 0.7), (' 2R21vXR83lH98kGeO99Y66', 0.5), (' 6M2wZ9GZgrQXHCFfjv46we', 0.5), ('1Cs0zKBU1kc0i8ypK3B9ai', 0.30000000000000004), (' 3MZsBdqDrRTJihTHQrO6Dq', 0.30000000000000004), (' 3TVXtAsR1Inumwj472S9r4', 0.30000000000000004), (' 4VMYDCV2IEDYJArk749S6m', 0.30000000000000004), (' 7Ln80lUS6He07XvHI8qqHH', 0.30000000000000004), (' 53XhwfbYqKCa1cC15pYq2q', 0.30000000000000004), ('0Y5tJX1MQlPlqiwlOH1tJY', 0.2), (' 2LRoIwlKmHjgvigdNGBHNo', 0.2), ('0du5cEVh5yTK9QJze8zA0C', 0.1), (' 1McMsnEElThX1knmY4oliG', 0.1), (' 1uNFoZAHBGtllmzznpCI3s', 0.1), (' 5f7VJjfbwm532GiveGC0ZK', 0.1), (' 5K4W6rqBFWDnAN6FQUkS6x', 0.1), (' 6LuN9FCkKOj5PcnpouEgny', 0.1), (' 716NhGYqD1jl2wI1Qkgq36', 0.1), (' 7dGJo4pcD2V6oG8kP0tJRR', 0.1), ('00FQb4jTyendYWaN8pK0wa', 0.1), (' 3Nrfpe0tUJi4K4DXYWgMUX', 0.1), (' 4O15NlyKLIASxsJ0PrXPfz', 0.1), (' 790FomKkXshlbRYZFtlgla', 0.1), ('0EmeFodog0BfCgMzAIvKQp', 0.0), (' 66CXWjxzNUsdJxJ2JdwvnR', 0.0), (' 6eUKZXaKkcviH0Ku9w2n3V', 0.0), (' 0Y5tJX1MQlPlqiwlOH1tJY', 0.0), (' 41MozSoPIsD1dJM0CLPjZF', 0.0), ('1VPmR4DJC1PlOtd0IADAO0', 0.0), (' 246dkjvS1zLTtiykXe5h60', 0.0), (' 4gzpq5DPGxSnKTe4SA8HAU', 0.0), (' 4q3ewBCX7sLwd24euuV69X', 0.0), (' 0du5cEVh5yTK9QJze8zA0C', 0.0), (' 0EmeFodog0BfCgMzAIvKQp', 0.0), (' 2YZyLoL8N0Wb9xBt1NhZWg', 0.0), (' 0hCNtLu0JehylgoiP8L4Gh', 0.0), (' 4YRxDV8wJFPHPTeXepOstw', 0.0), (' 5pKCCKE2ajJHZ9KAiaK11H', 0.0), (' 7bXgB6jMjp9ATFy66eO08Z', 0.0), (' 7ltDVBr6mKbRvohxheJ9h1', 0.0), (' 1RyvyyTE3xzB2ZywiAwp0i', 0.0), (' 1vyhD5VmyZ7KMfW5gqLgo5', 0.0), (' 1Xyo4u8uXC1ZmMpatF05PJ', 0.0), ('1i8SpTcr7yvPOmcqrbnVXY', 0.0), (' 1Cs0zKBU1kc0i8ypK3B9ai', 0.0), ('2LRoIwlKmHjgvigdNGBHNo', 0.0), (' 6qqNVTkY8uBg9cP3Jd7DAH', 0.0), ('1vyhD5VmyZ7KMfW5gqLgo5', 0.0), (' 6vWDO969PvNqNYHIOW5v0m', 0.0), (' 1mcTU81TzQhprhouKaTkpq', 0.0), (' 4MCBfE4596Uoi2O4DtmEMz', 0.0), (' 1URnnhqYAYcrqrcwql10ft', 0.0), (' 1VPmR4DJC1PlOtd0IADAO0', 0.0), (' 1i8SpTcr7yvPOmcqrbnVXY', 0.0), ('0hCNtLu0JehylgoiP8L4Gh', 0.0), (' 6KImCVD70vtIoJWnq6nGn3', 0.0), ('4O15NlyKLIASxsJ0PrXPfz', 0.0), (' 5cj0lLjcoR7YOSnhnX0Po5', 0.0), ('1RyvyyTE3xzB2ZywiAwp0i', 0.0), (' 15UsOTVnJzReFVN1VCnxy4', 0.0), ('1URnnhqYAYcrqrcwql10ft', 0.0), ('6LuN9FCkKOj5PcnpouEgny', 0.0), ('2R21vXR83lH98kGeO99Y66', 0.0), ('15UsOTVnJzReFVN1VCnxy4', 0.0), ('1McMsnEElThX1knmY4oliG', 0.0)]